{
  "Parameters":
    {
      "VpcCIDR": "10.0.0.0/16",
      "PublicSubnet1CIDR": "10.0.1.0/24",
      "PublicSubnet2CIDR": "10.0.2.0/24",
      "InstanceType": "t2.micro",
      "ImageId": "ami-0953476d60561c955",
    },
}
